### ISSUE TITLE
VGG16预训练模型

### ISSUE THREAD

**Issue by chuangchuangtan** [PengtaoJiang/LayerCAM-jittor#6]
请问论文中表1、表2中的WSOL结果是用什么VGG16预训练模型跑的，pytorch官方的还是自己训练的？如果是自己训练的模型，请问是否能提供？非常感谢！！

**Comment by PengtaoJiang** [comment]
Hi, 你好，我用的是caffe中的VGG模型转成pytorch的模型，模型链接: https://pan.baidu.com/s/1e8EPSGWA08gl5KE0v-1MEw  密码: 78wp。名称是VGG-16-caffe.pth

**Comment by noobgrow** [comment]
大神您好，请教下文章中 ILSVRC弱监督定位能力实验中 bbox真值是如何得到的？我该如何获得真值标签？非常感谢！！

**Comment by PengtaoJiang** [comment]
@chuangchuangtan https://github.com/PengtaoJiang/layercam_loc

**Comment by PengtaoJiang** [comment]
在这个代码里面 https://github.com/PengtaoJiang/layercam_loc

发件人：Dong ***@***.***>
发送日期：2022-03-18 21:22:31
收件人：PengtaoJiang/LayerCAM-jittor ***@***.***>
抄送人：Jiangpengtao ***@***.***>,Comment ***@***.***>
主题：Re: [PengtaoJiang/LayerCAM-jittor] VGG16预训练模型 (Issue #6)

大神您好，请教下文章中 ILSVRC弱监督定位能力实验中 bbox真值是如何得到的？我该如何获得真值标签？非常感谢！！
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
